### ISSUE TITLE
Named Slots

### ISSUE THREAD

**Issue by jbrozek** [riot/examples#106]
https://plnkr.co/edit/mw6VQTqFrCr9r9wL

I'm attempting to use the named slots feature, seems straight forward.  The rendering here is not in the order I would expect.

Am I doing something incorrect?

**Comment by GianlucaGuarini** [comment]
From our doc https://riot.js.org/documentation/#slots:

> Slots only work in compiled components. All of the inner HTML of the components placed directly in your page DOM will be ignored.
