### ISSUE TITLE
todo-app and todo-app-precompiled are different

### ISSUE THREAD

**Issue by Aprillion** [riot/examples#17]
There is an extra X1 button on http://riotjs.com/examples/todo-app/ which is not present on http://riotjs.com/examples/todo-app-precompiled/ (on Win 10, Firefox 42.0, no errors in the console for either app)
![riot_todo_x1_button](https://cloud.githubusercontent.com/assets/1087670/11671561/ac37c86a-9e09-11e5-8311-9b0ed8b5f29f.png)

The 2 examples are listed as comparable on http://riotjs.com/guide/compiler/#demos, I have no idea which version of the app is correct.

Expected:
it should be the same app

(P.S.: no time to fix this myself this week)

**Comment by cognitom** [comment]
@Aprillion thanks for reporting. I've recompiled the tag file. Now it seems OK ;-)
