### ISSUE TITLE
Cannot read property 'first' of undefined

### ISSUE THREAD

**Issue by believer-ufa** [riot/examples#25]
I cant run this example in plunker :(

http://plnkr.co/edit/XRQXCmKgOlyDEDHQ06wY?p=preview

`Cannot read property 'first' of undefined list.tag[51]`

**Comment by GianlucaGuarini** [comment]
I need to fix this, I will try to figure out where is the issue

**Comment by believer-ufa** [comment]
In you browser you example work fine? I use Chrome 48.

**Comment by GianlucaGuarini** [comment]
it does not work..

> I need to fix this, I will try to figure out where is the issue

**Comment by believer-ufa** [comment]
I fixed it: http://plnkr.co/edit/GDMHOY7jgo31yALSPBs9?p=preview

**Comment by GianlucaGuarini** [comment]
it seems that this issue comes from riot, the `update` event gets triggered before the `mount`. We need to fix the issue in riot and not in the example

**Comment by believer-ufa** [comment]
Yes, i think about it, but thought that I was doing something wrong.

**Comment by GianlucaGuarini** [comment]
I have fixed the demo, the riot core issue raised up by this example will be a breaking change and it will be introduced in riot 3.0.0. Thanks for your help
