### ISSUE TITLE
examples/webpack:  cannot render  sub component <logs> 

### ISSUE THREAD

**Issue by silentzone** [riot/examples#33]
![image](https://cloud.githubusercontent.com/assets/273957/18424867/4ff0a424-78e6-11e6-93d6-fab10c2ab96a.png)

```
require('./random.tag') 
riot.mount('random', {
  title: 'Random number generator!'
})
riot.mount('logs', {
  title: ''
})
```

add code   mount 'logs' the sub component can reander but not work parent is undefine

**Comment by silentzone** [comment]
is close. find way to solve

**Comment by JrSchild** [comment]
Have you found a solution to this?

**Comment by GianlucaGuarini** [comment]
I will check this asap

**Comment by GianlucaGuarini** [comment]
I have checked the example and I don't see any problem
