### ISSUE TITLE
Refresh Problem with Router - Complex example

### ISSUE THREAD

**Issue by ghost** [riot/examples#36]
I tried router-complex example, everything works nice but i noticed that when i refresh the page
```
localhost:3000/first/apple
```
it throws back Syntax error and i'm basically seeing nothing on the screen. I'm trying to make a SPA for my portfolio, and want to format the url structure like
```
/{works}/{project_id} 
```
wish i could solve this problem myself..any suggestions?
![2016-11-02 19 04 09](https://cloud.githubusercontent.com/assets/6639567/19924673/50f93454-a130-11e6-99ed-203a5506e9e0.png)

**Comment by GianlucaGuarini** [comment]
@no-wa-ke please make a live example to allow us to check your issue, remember that if you want to use html5 history navigation you need to configure your server properly [google search](https://www.google.ch/search?q=html5+history+server+configuration&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=RL8ZWPqCIqvC8gecxqvQBQ)

**Comment by ghost** [comment]
@GianlucaGuarini thank for your quick reply. Well, I used superstatic for the server as the config file were given in the example. I added 

```
<base href="/">
```

on top of index.html and fixed the problem. Here are some live examples.(I'm using express as a middleware for pushstate-server )

without base tag:
http://riot-router-example.herokuapp.com/first/apple

with base tag:
http://riot-router-example-with-base.herokuapp.com/first/apple

**Comment by GianlucaGuarini** [comment]
@no-wa-ke please would you mind making a pull request?

**Comment by ghost** [comment]
@GianlucaGuarini added on Pull #37

**Comment by cognitom** [comment]
Hi. As I mentioned on the PR, we need to care about our demo page.
http://riotjs.com/examples/router-complex/
In the page, we should use `<base href="/examples/">`.

Actually, GitHub Pages doesn't support settings around HTML5 history navigation, so our page doesn't, either. That's also the point we have to fix, related to this issue...
I think we need to fork the example into _HTML5 history version_ and _hash version_ of it.

@GianlucaGuarini I'd like to convert this example into _hash version_ and create another new example of _HTML5 history_, can I?

**Comment by GianlucaGuarini** [comment]
@cognitom yes go on thanks

**Comment by cognitom** [comment]
OK, will do 😄 
@no-wa-ke I'll make another PR, asap. Could you check that later? Thanks!

**Comment by cognitom** [comment]
OK, done.
@GianlucaGuarini could you pls merge #38, when you have time.

**Comment by ghost** [comment]
@cognitom works like a charm, thank you !
