### ISSUE TITLE
examples/todo-app-precompiled: mistake version and cannot run

### ISSUE THREAD

**Issue by kkeeth** [riot/examples#41]
At `todo-app-precompiled/index.html`, 
```
<script src="https://cdn.rawgit.com/riot/riot/master/riot.min.js"></script>
```
the version of riot.js in this URL is `v2.6.7`!
So, I changed the URL to `https://rawgit.com/riot/riot/next/riot.min.js` and displayed index.html in the browser, it was displayed as follows.

![todo-app-precompiled](https://cloud.githubusercontent.com/assets/4125257/20377787/2905cbc8-acd5-11e6-99d8-e7759e690af9.png)

And in this state I tried running the application, but I could not add or delete todo.

**Comment by cognitom** [comment]
Hi, @k-kuwahara san, nice catch. It should point to `next` branch.
https://rawgit.com/riot/riot/next/riot.min.js

Could you pls send PR about this? Thanks.

**Comment by cognitom** [comment]
Thanks for your contribution #42! I've added your name to #39 😉
