### ISSUE TITLE
examples/todo-app: cannot get the input value

### ISSUE THREAD

**Issue by kkeeth** [riot/examples#43]
I try to run`todo-app` on [plunker](https://plnkr.co/edit/JYyTe9zzc4sTcjLP5o0w?p=preview), but the following error was output to console on `add` method. Since version 3.0.0, can we get the value of input tag specified by the value of `name`?

![todo-app](https://cloud.githubusercontent.com/assets/4125257/20379463/be1fc93e-acdf-11e6-991e-a69b25736e85.png)

**Comment by cognitom** [comment]
Oh, a good point, that's a deprecated feature. We need to use `ref` attributes instead of `name` or `id`.
https://plnkr.co/edit/0yK3vigCfCnD2HKZrTn2?p=preview

**Comment by kkeeth** [comment]
@cognitom Thank you for your reply! It's ok. I'll send PR.

**Comment by cognitom** [comment]
Fixed in #44
