### ISSUE TITLE
examples/webpack: mistake version

### ISSUE THREAD

**Issue by kkeeth** [riot/examples#46]
Please this capture, the version of riotjs is `v2.6.7` in `bundle.js`.

![2016-11-20 14 24 09](https://cloud.githubusercontent.com/assets/4125257/20460684/8754dee8-af2e-11e6-8721-0969b0363316.png)

**Comment by cognitom** [comment]
Update needed.
https://github.com/esnunes/riotjs-loader/blob/master/package.json#L31

Could you pls [make a new issue](https://github.com/esnunes/riotjs-loader/issues) there?

**Comment by kkeeth** [comment]
@cognitom 
oh! I see.
I sent a PR to @esnunes.

So, I close this issue.

**Comment by cognitom** [comment]
Thanks!
