### ISSUE TITLE
Plunker .tag files syntax

### ISSUE THREAD

**Issue by believer-ufa** [riot/examples#48]
If you add .tag files on Plunker, it dont set syntax highlighting. Maybe rename all examples files to `.html` extensions?

For example, todo app: http://plnkr.co/edit/uQp4fVG0TW6jeKkcW34g?p=preview
You original: http://riotjs.com/examples/plunker/?app=todo-app

Select todo.tag file and try to change it ))

**Comment by GianlucaGuarini** [comment]
@believer-ufa we don't own plunker and we can not do anything to solve this issue. Keep using the html extension on plunker since riot does not really care about file extensions
