### ISSUE TITLE
Live filtering example doesn't work

### ISSUE THREAD

**Issue by rajus-git** [riot/examples#53]
There is something wrong with Live filtering example. Yahoo changed the API or something? The example does not work out of the box and should be fixed.

**Comment by GianlucaGuarini** [comment]
@cognitom could you please have a look at it?

**Comment by cognitom** [comment]
@Rajas-Git thanks for reporting!

> Yahoo changed the API or something?

Yeah, it looks so. It happened last year according to StackOverflow.
http://stackoverflow.com/questions/38355075/has-yahoo-finance-web-service-disappeared-api-changed-down-temporarily

This API still works well, but there's no support for `jsonp` now...
http://finance.yahoo.com/webservice/v1/symbols/allcurrencies/quote?format=json

Unfortunately, the response header has no `Access-Control-Allow-Origin` field, so we can't use this from browsers. I think we need to find an alternative.

**Comment by cognitom** [comment]
It seems exactly what we're looking for!
http://fixer.io/
