### ISSUE TITLE
Question on example: animated-list-reordering

### ISSUE THREAD

**Issue by fabien** [riot/examples#54]
@cognitom I was looking through this example `animated-list-reordering` and was wondering about this particular comment: https://github.com/riot/examples/blob/gh-pages/animated-list-reordering/list.tag#L57

I tried to add items and update the flip instance accordingly, but I was unsuccessful. I have used the FLIP technique before, but not within the context of Riot. I don't see where you'd update the items and update the flip instance to make this work. Did you try something like this in Riot?

**Comment by cognitom** [comment]
@fabien thanks for reporting! This example was made by @GianlucaGuarini . It seems better to ask him about it 😄

**Comment by fabien** [comment]
@GianlucaGuarini thanks!
