### ISSUE TITLE
Rollup plugin failed to parse a tag in certain condition

### ISSUE THREAD

**Issue by bmikeb** [riot/examples#55]
Hello,

My app uses a tag
`<my-tag style="height:{height}px"> <my-tag>
...
this.height=100`

Riot compiler does make its work fine, while rollup plugin fires an error. If instead of inline styling I'm using a `{class:class}`, all worked fine though.

Mikhail

**Comment by cognitom** [comment]
Hello @bmikeb, pls open your issue at [rollup-plugin-riot](https://github.com/riot/rollup-plugin-riot/issues). Thanks.
