### ISSUE TITLE
Issue with yielding data from <calendar> to <btn> (riot-bootstrap)

### ISSUE THREAD

**Issue by bmikeb** [riot/examples#58]
Hi there,
I found that `{daynum}` value isn't passed correctly to `<btn>` tag (in v.3 only), so days aren't displayed.
```
<tbody>
  <tr><th each={ day in weekdays }>{ day }</th></tr>
  <tr each={ week in calendar }>
    <td each={ week }>
      <btn active={ selected } disabled={ !currentMonth } onclick={ dayclick }>{ daynum }</btn>
    </td>
  </tr>
</tbody>
```
Though in v.2.5 yielding works fine.

**Comment by GianlucaGuarini** [comment]
@bmikeb this is the wrong project.. try submitting the issue [here](https://github.com/cognitom/riot-bootstrap)
