### ISSUE TITLE
What is the most up-to-date recommended seed/setup for latest riot version (3.11)?

### ISSUE THREAD

**Issue by dharmax** [riot/examples#63]
What is the most elegant way to get a riot based UI today?

i'd love the following points to be addressed:

1. A proper code-mapping for easy debugging
2. A good way to bundle the application (so far i used Webpack and JSPM)
3. It would be lovely if it would work elegantly with Typescript.
4. Is it best to use Tag files, or straight JS? If the later, would it be better to use a class that inherit from riot's tag class? If so, can i place the template code in a different file?
5. Future compatibility: i saw that there's going to be a change (that "export default" thing) - how would you recommend to write the code for the smoothest migration path?

If you have more items for consideration - please add them....

Note that this is also posted on stackoverflow, but there were zero answers there: https://stackoverflow.com/questions/51588560/what-is-the-most-up-to-date-recommended-seed-setup-for-latest-riot-version-3-11

**Comment by GianlucaGuarini** [comment]
I have answered on stackoverflow since this is not really an issue. I close this one avoiding to have the same contents in 2 different places
