### ISSUE TITLE
Code-splitting bundle.js

### ISSUE THREAD

**Issue by anonimusprogramus** [riot/examples#70]
Current Rollup example works well, outputting one file bundle.js with iife format.

But when the size of bundle.js grows bigger, perhaps we need advanced Rollup (or Webpack/Parcel) configuration which enables minify, code-split, dynamic imports, etc.

It would be a great help if this enhancement can be applied on current v4 examples.

Thanks.

**Comment by GianlucaGuarini** [comment]
https://github.com/riot/examples/tree/gh-pages/lazy-routes
