### ISSUE TITLE
Migrate remaining examples to riot4

### ISSUE THREAD

**Issue by hudelgado** [riot/examples#74]
Hi, if you need i can migrate the examples that aren't updated to riot4.

**Comment by GianlucaGuarini** [comment]
@hudelgado that would be great wherever it's possible. I think the router examples need to be on hold because the new Riot Router was not released yet. For all the others your help would be really appreciated. Thank you

**Comment by raxell** [comment]
Does make sense to migrate the [mixin example](https://github.com/riot/examples/tree/gh-pages/wip/mixins)? It seems equivalent to the [plugin example](https://riot.js.org/documentation/#plugins) in the doc.

**Comment by GianlucaGuarini** [comment]
naa we can delete it
