### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by SassNinja** [riot/examples#80]
## Help us to manage our issues by answering the following:

1. Describe your issue:

I'm trying to use riot v4 with IE11 and added all required polyfills.
However even with it the code throws an error:
```
Unable to get property 'removeAttribute' of undefined or null reference
```

Any idea how to fix this or rather is riot v4 supposed to be used with IE11?

Here's my code

**index.html**
```html
<my-list></my-list>
<script crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?features=Object.values%2CArray.from%2CObject.assign%2CCustomEvent%2CSymbol%2CObject.entries"></script>
<script src="index.js"></script>
```

**index.js**
```javascript
import MyList from './my-list.riot'
import {component} from 'riot'

component(MyList)(document.querySelector('my-list'), {
    items: ['apple', 'orange', 'banana']
})
```

**my-list.riot**
```html
<my-list>
    <ul if={ props.items }>
        <li each={ item in props.items }>{ item }</li>
    </ul>
</my-list>
```

2. Can you reproduce the issue?

  see above

3. On which browser/OS does the issue appear?

IE11, Win7

4. Which version of Riot does it affect?

Any

5. How would you tag this issue?

  - [x] Question
  - [x] Bug
  - [ ] Discussion
  - [ ] Feature request
  - [ ] Tip
  - [ ] Enhancement
  - [ ] Performance

**Comment by GianlucaGuarini** [comment]
I will create a working IE11 example with Riot.js 4 I think it's the easiest path to take here

**Comment by lxndrdagreat** [comment]
Thank you so much! I absolutely love what you've been doing with Riot 4 and would like to have my team using it.

**Comment by hairlesshobo** [comment]
> I had to polyfill many native browser features and create a bundle via babel only for IE11 but Riot.js 4 can definitely work on ie11 it's just not supported out of the box:
> 
> https://plnkr.co/edit/DLGFc6W0vUZcWqsnbfsR?p=preview

OK.. this saved me!!

I've been struggling for two days to get my app to work in IE11 (for corp intranet compatibility) and getting riot to play nice was the last issue I was encountering. That example with the web components template was exactly what I was missing!!

Thank you very much!!
