### ISSUE TITLE
Webpack example doesn't work

### ISSUE THREAD

**Issue by PseudoMon** [riot/examples#89]
I copied the entirety of the webpack example folder and installed all the dependencies. When I run `npm start`, I got this error:

```
ERROR in ./app/random.riot
andom.riot' in 'C:\[redacted]\riotjs\webpack\app's
@ ./app/random.riot 109:24-89
@ ./app/main.js

ERROR in ./app/logs.riot
iotjswebpackapplogs.riot' in 'C:\[redacted]\riotjs\webpack\app's
@ ./app/logs.riot 54:24-89
@ ./app/random.riot
@ ./app/main.js
   ?wdm?: Failed to compile.
```

I'm still pretty new to using Webpack, so I'm not sure what's causing it.

**Comment by GianlucaGuarini** [comment]
I have just checked the webpack example `cd webpack && npm i && npm start` and it worked perfectly. Please make sure your problem is not somewhere else. It would be great also if you could reproduce the issue on https://codesandbox.io/
