### ISSUE TITLE
DOMException Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by lucabassplayer89** [riot/examples#90]
hi all,
i don't understand this exception in my riot v4 project.
The message is:
riot+compiler.js?v=dd6adea73093a1cdadf25239d0e45752:881 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
If i refresh the browser page the error doesn't appear...

**Comment by GianlucaGuarini** [comment]
Please open an issue here with a Demo that we could test https://github.com/riot/riot. Thank you
