### ISSUE TITLE
checked checkbox when deleting todo item

### ISSUE THREAD

**Issue by desudo** [riot/examples#91]
Copied the todo app [https://riot.js.org/documentation/#todo-example](https://riot.js.org/documentation/#todo-example) and added some extra features like deleting checked items.

When deleting a checked item, the checkbox of the next item in the list becomes checked although it does not have the attribute "checked" or the property "done" ins the items object.

This can be solved by either giving each item the property "done: false" as default or in the riot tag asking in the loop if item.done === true to check the item.

Is this a known issue which was meant to be as specific as possible?

**Comment by GianlucaGuarini** [comment]
@desudo please check the `key` attribute as recommended by the documentation https://riot.js.org/documentation/#loops-advanced-tips

**Comment by SassNinja** [comment]
when using `key` that issue doesn't appear

however you don't always have a key or rather immutable collections...
seems the state update doesn't handle this properly because `checked={ undefined }` works as expected on initial rendering and only causes this issue on update
